sudo: false
language: node_js
node_js:
  - '0.12'
  - '4'
  - 'stable'
before_install:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
  - npm install -g bower
before_script:
  - npm install -g grunt-cli
script:
  - grunt dev
  - grunt build
